// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: dockerhandle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Info:
	//	*OperationRequest_ContainerId
	//	*OperationRequest_Data
	Info isOperationRequest_Info `protobuf_oneof:"info"`
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dockerhandle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhandle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_dockerhandle_proto_rawDescGZIP(), []int{0}
}

func (m *OperationRequest) GetInfo() isOperationRequest_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (x *OperationRequest) GetContainerId() string {
	if x, ok := x.GetInfo().(*OperationRequest_ContainerId); ok {
		return x.ContainerId
	}
	return ""
}

func (x *OperationRequest) GetData() []byte {
	if x, ok := x.GetInfo().(*OperationRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isOperationRequest_Info interface {
	isOperationRequest_Info()
}

type OperationRequest_ContainerId struct {
	ContainerId string `protobuf:"bytes,1,opt,name=containerId,proto3,oneof"`
}

type OperationRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*OperationRequest_ContainerId) isOperationRequest_Info() {}

func (*OperationRequest_Data) isOperationRequest_Info() {}

type DialogueReplyMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Errormes string `protobuf:"bytes,3,opt,name=errormes,proto3" json:"errormes,omitempty"`
	Duration int32  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` //operte duration second
}

func (x *DialogueReplyMeta) Reset() {
	*x = DialogueReplyMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dockerhandle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogueReplyMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueReplyMeta) ProtoMessage() {}

func (x *DialogueReplyMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhandle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueReplyMeta.ProtoReflect.Descriptor instead.
func (*DialogueReplyMeta) Descriptor() ([]byte, []int) {
	return file_dockerhandle_proto_rawDescGZIP(), []int{1}
}

func (x *DialogueReplyMeta) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DialogueReplyMeta) GetErrormes() string {
	if x != nil {
		return x.Errormes
	}
	return ""
}

func (x *DialogueReplyMeta) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type DialogueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Info:
	//	*DialogueReply_Data
	//	*DialogueReply_Meta
	Info isDialogueReply_Info `protobuf_oneof:"info"`
}

func (x *DialogueReply) Reset() {
	*x = DialogueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dockerhandle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueReply) ProtoMessage() {}

func (x *DialogueReply) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhandle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueReply.ProtoReflect.Descriptor instead.
func (*DialogueReply) Descriptor() ([]byte, []int) {
	return file_dockerhandle_proto_rawDescGZIP(), []int{2}
}

func (m *DialogueReply) GetInfo() isDialogueReply_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (x *DialogueReply) GetData() string {
	if x, ok := x.GetInfo().(*DialogueReply_Data); ok {
		return x.Data
	}
	return ""
}

func (x *DialogueReply) GetMeta() *DialogueReplyMeta {
	if x, ok := x.GetInfo().(*DialogueReply_Meta); ok {
		return x.Meta
	}
	return nil
}

type isDialogueReply_Info interface {
	isDialogueReply_Info()
}

type DialogueReply_Data struct {
	Data string `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type DialogueReply_Meta struct {
	Meta *DialogueReplyMeta `protobuf:"bytes,2,opt,name=meta,proto3,oneof"`
}

func (*DialogueReply_Data) isDialogueReply_Info() {}

func (*DialogueReply_Meta) isDialogueReply_Info() {}

type GetPullImageLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageId string `protobuf:"bytes,1,opt,name=imageId,proto3" json:"imageId,omitempty"`
}

func (x *GetPullImageLogRequest) Reset() {
	*x = GetPullImageLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dockerhandle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPullImageLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullImageLogRequest) ProtoMessage() {}

func (x *GetPullImageLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhandle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullImageLogRequest.ProtoReflect.Descriptor instead.
func (*GetPullImageLogRequest) Descriptor() ([]byte, []int) {
	return file_dockerhandle_proto_rawDescGZIP(), []int{3}
}

func (x *GetPullImageLogRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type GetContainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
}

func (x *GetContainerRequest) Reset() {
	*x = GetContainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dockerhandle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerRequest) ProtoMessage() {}

func (x *GetContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhandle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerRequest.ProtoReflect.Descriptor instead.
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return file_dockerhandle_proto_rawDescGZIP(), []int{4}
}

func (x *GetContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_dockerhandle_proto protoreflect.FileDescriptor

var file_dockerhandle_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x54, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x5f,
	0x0a, 0x11, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x5a, 0x0a, 0x0d, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x32, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x50, 0x75, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x32, 0xd3, 0x01, 0x0a, 0x0c, 0x44, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x75, 0x6c, 0x6c,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x75, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42, 0x53,
	0x0a, 0x13, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x62, 0x42, 0x0c, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x75, 0x6f, 0x72, 0x75, 0x6f, 0x66, 0x65, 0x6e, 0x67, 0x2f, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dockerhandle_proto_rawDescOnce sync.Once
	file_dockerhandle_proto_rawDescData = file_dockerhandle_proto_rawDesc
)

func file_dockerhandle_proto_rawDescGZIP() []byte {
	file_dockerhandle_proto_rawDescOnce.Do(func() {
		file_dockerhandle_proto_rawDescData = protoimpl.X.CompressGZIP(file_dockerhandle_proto_rawDescData)
	})
	return file_dockerhandle_proto_rawDescData
}

var file_dockerhandle_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dockerhandle_proto_goTypes = []interface{}{
	(*OperationRequest)(nil),       // 0: pb.OperationRequest
	(*DialogueReplyMeta)(nil),      // 1: pb.DialogueReplyMeta
	(*DialogueReply)(nil),          // 2: pb.DialogueReply
	(*GetPullImageLogRequest)(nil), // 3: pb.GetPullImageLogRequest
	(*GetContainerRequest)(nil),    // 4: pb.GetContainerRequest
}
var file_dockerhandle_proto_depIdxs = []int32{
	1, // 0: pb.DialogueReply.meta:type_name -> pb.DialogueReplyMeta
	0, // 1: pb.DockerHandle.Operation:input_type -> pb.OperationRequest
	3, // 2: pb.DockerHandle.GetPullImageLog:input_type -> pb.GetPullImageLogRequest
	4, // 3: pb.DockerHandle.GetContainerLog:input_type -> pb.GetContainerRequest
	2, // 4: pb.DockerHandle.Operation:output_type -> pb.DialogueReply
	2, // 5: pb.DockerHandle.GetPullImageLog:output_type -> pb.DialogueReply
	2, // 6: pb.DockerHandle.GetContainerLog:output_type -> pb.DialogueReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dockerhandle_proto_init() }
func file_dockerhandle_proto_init() {
	if File_dockerhandle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dockerhandle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dockerhandle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogueReplyMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dockerhandle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dockerhandle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPullImageLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dockerhandle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dockerhandle_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OperationRequest_ContainerId)(nil),
		(*OperationRequest_Data)(nil),
	}
	file_dockerhandle_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*DialogueReply_Data)(nil),
		(*DialogueReply_Meta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dockerhandle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dockerhandle_proto_goTypes,
		DependencyIndexes: file_dockerhandle_proto_depIdxs,
		MessageInfos:      file_dockerhandle_proto_msgTypes,
	}.Build()
	File_dockerhandle_proto = out.File
	file_dockerhandle_proto_rawDesc = nil
	file_dockerhandle_proto_goTypes = nil
	file_dockerhandle_proto_depIdxs = nil
}
